### ISSUE TITLE
Tickets information

### ISSUE THREAD

**Issue by 55** [apidaysnordic/apidaysnordic.github.io#1]
How many ticket types do we have?
What are the prices and their conditions?

**Comment by kyyberi** [comment]
- 150 tickets. 
- Prices are still hanging. Just one ticket type. Price will go higher the later you purchase. 
- Tickets price is defined at noon at organizer skype meetup. On the page there is in comments a structure for the tickets (see from source for example from index page or tickets subpage.

**Comment by 55** [comment]
Thanks. Also got additional information on tickets from Chandra. So, closing this.
